name: 'generate-changelog-action'
description: 'GitHub Action for lob/generate-changelog'
author: 'Scott Brenner'
outputs:
  changelog:
    description: 'Generate changelog'
inputs:
  package-dir:
    description: 'The path for the package.json if it is not in root'
    required: false
    default: 'package.json'
  from-tag:
    description: 'The tag to generate changelog from'
    required: false
    default: ''
  to-tag:
    description: 'The tag to generate changelog up to'
    required: false
    default: ''
  type:
    description: 'Type of changelog: patch, minor, or major'
    required: false
    default: ''
  exclude:
    description: 'Exclude selected commit types (comma separated)'
    required: false
    default: ''
  allow-unknown:
    description: 'Allow unknown commit types'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PACKAGE_DIR: ${{ inputs.package-dir }}
    FROM_TAG: ${{ inputs.from-tag }}
    TO_TAG: ${{ inputs.to-tag }}
    TYPE: ${{ inputs.type }}
    EXCLUDE: ${{ inputs.exclude }}
    ALLOW_UNKNOWN: ${{ inputs.allow-unknown }}
branding:
  icon: 'edit'
  color: 'gray-dark'
