name: 'generate-changelog-action'
description: 'GitHub Action for lob/generate-changelog'
author: 'Scott Brenner'
outputs:
  changelog:
    description: 'Generate changelog'
inputs:
  package-dir:
    description: 'The path for the package.json if it is not in root'
    required: false
    default: 'package.json'
  from-tag:
    description: 'The tag to generate changelog from'
    required: false
    default: ''
  to-tag:
    description: 'The tag to generate changelog up to'
    required: false
    default: ''        
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-dir }}
  env:
    FROM_TAG: ${{ inputs.from-tag }}
    TO_TAG: ${{ inputs.to-tag }}
branding:
  icon: 'edit'
  color: 'gray-dark'
